In [1]:
#to access numPy library, the import must be be used:
import numpy as np

In storing array it should be same type and same size

## Python Demo 1: Creating and Inspecting ndarrays

In [2]:
#1D Array - vector
el = np.array([1,2,3])
el

# el = [1 2 3]

array([1, 2, 3])

In [3]:
#2D Array - matrix
psy = np.array([(2.4, -1.5,1.1), (2.3,-2.5,-5.6)])
psy
               
# psy = [ 2.4, -1.5,  1.1],
#       [ 2.3, -2.5, -5.6]

array([[ 2.4, -1.5,  1.1],
       [ 2.3, -2.5, -5.6]])

In [4]:
#3D Array - tensor
kongroo = np.array([[(1.1,2,3.4), (7,2.5,9)], [(1,2,3), (9,8,7)]])
kongroo

# kongroo =

array([[[1.1, 2. , 3.4],
        [7. , 2.5, 9. ]],

       [[1. , 2. , 3. ],
        [9. , 8. , 7. ]]])

In [5]:
#Create an array of m x n x p zeros
x = np.zeros((2,3)) #2 rows, 3 columns
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
y = np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#Syntax: np.arange(first:last-interval:interval)

z = np.arange(3,7,0.5)
z

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [8]:
#Syntax: np.linspace(first:last:number pf samples)
np.linspace(3,7,10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [9]:
np.full((5,3),12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [10]:
# identify matrix: np.eye(m)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.random((2,3))

array([[0.23108667, 0.46220859, 0.47641212],
       [0.41621438, 0.87087138, 0.77300949]])

In [12]:
#Viewing the contents on a numpy life
#Syntax - np.load('filename.npy')
data = np.load('epk.npy')
data

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [13]:
data.shape

(2, 2, 3)

In [14]:
data.ndim

3

In [15]:
data.size

12

## Pyhton Demo 2: Arithmetic and Logical Operations on Arrays

In [16]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
b = np.array([(4,9),(16,25),(36,49)])
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [18]:
c = np.array([2,3,5])
c

array([2, 3, 5])

In [19]:
#Element-wise
c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [20]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [21]:
a*c

array([[ 4, 12, 30],
       [16, 30, 60]])

In [22]:
c*a

array([[ 4, 12, 30],
       [16, 30, 60]])

In [23]:
a/c

array([[1.        , 1.33333333, 1.2       ],
       [4.        , 3.33333333, 2.4       ]])

In [24]:
c/a

array([[1.        , 0.75      , 0.83333333],
       [0.25      , 0.3       , 0.41666667]])

In [25]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [26]:
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [27]:
np.exp(b)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [28]:
np.sqrt(b)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [29]:
np.cos(b)

array([[-0.65364362, -0.91113026],
       [-0.95765948,  0.99120281],
       [-0.12796369,  0.30059254]])

In [30]:
np.log(b)

array([[1.38629436, 2.19722458],
       [2.77258872, 3.21887582],
       [3.58351894, 3.8918203 ]])

In [31]:
np.cos(b)

array([[-0.65364362, -0.91113026],
       [-0.95765948,  0.99120281],
       [-0.12796369,  0.30059254]])

In [32]:
a = np.array([2, 3, 5])
a

array([2, 3, 5])

In [33]:
b = np.array([(1,2,5), (4,5,6), (7,8,9)])
b

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# = is an assignment operator
c = a
a

array([2, 3, 5])

In [35]:
#Element-wise
a == b

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [36]:
b < 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [37]:
a > 2

array([False,  True,  True])

In [38]:
#As a group
np.array_equal(a,b)

False

In [39]:
np.array_equal(a,c)

True

## Python Demo 3: Subsetting, Slicing and Indexing of Arrays

In [40]:
A = np.array([(1,2,3), (4,5,6), (7,8,9)])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Subsetting- getting a certain element from the array or structure

In [41]:
A[1,1] #or A[1][1]

5

In [42]:
A[2,1]

8

#### Slicing - getting the portion from an array or structure

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
A[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [45]:
A[1:2]

array([[4, 5, 6]])

In [46]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
A[0:3,2]

array([3, 6, 9])

In [48]:
A[1]

array([4, 5, 6])

#### Indexing - getting a certain element or portion depending on the conditions

In [49]:
A[A<7]

array([1, 2, 3, 4, 5, 6])

In [50]:
A[A>2]

array([3, 4, 5, 6, 7, 8, 9])

In [51]:
A[A==5] #COUNTING and list down the number, kahit dalawa or tatlo pa
        #it just extracts the value from the array

array([5])

## Python Demo 4: ndarray Manipulation

In [52]:
a = np.array([3,2,1])
a

array([3, 2, 1])

In [53]:
b = np.array([(4,6,5),(3,2,1)])
b

array([[4, 6, 5],
       [3, 2, 1]])

In [54]:
c = np.linspace(10,20,3)
c

array([10., 15., 20.])

In [55]:
d = np.full((2,2),7)
d

array([[7, 7],
       [7, 7]])

In [56]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [57]:
a.sort()
a

array([1, 2, 3])

In [58]:
b

array([[4, 6, 5],
       [3, 2, 1]])

In [59]:
b.sort(axis = 0) #pag axis 0 by row
b

array([[3, 2, 1],
       [4, 6, 5]])

In [60]:
b.sort(axis=1)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.shape(b)

(2, 3)

In [62]:
b.reshape(6,1).shape

(6, 1)

In [63]:
b.resize(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
d

array([[7, 7],
       [7, 7]])

In [65]:
e

array([[1., 0.],
       [0., 1.]])

In [66]:
np.append(d,e)

array([7., 7., 7., 7., 1., 0., 0., 1.])

In [67]:
a

array([1, 2, 3])

In [68]:
np.insert(a,1,5) #yung nasa gitna corresponds to the location

array([1, 5, 2, 3])

In [69]:
np.delete(a,[2])

array([1, 2])

In [70]:
np.concatenate((a,c),axis=0)

array([ 1.,  2.,  3., 10., 15., 20.])

In [71]:
np.vstack((a,c))

array([[ 1.,  2.,  3.],
       [10., 15., 20.]])

In [75]:
np.hstack((d,e))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [73]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [74]:
np.vsplit(e,2)

[array([[1., 0.]]), array([[0., 1.]])]